### ISSUE TITLE
Is there any way can add jvmArgs to generate jacoco report

### ISSUE THREAD

**Issue by chengxinxing-airwallex** [tsundberg/gradle-cucumber-runner#7]
I want to generate jacoco report from cucumber tests in gradle koltin dsl. Is there any way that I can add a JaCoCo Agent jar with this jvm Argument? @tsundberg 
https://stackoverflow.com/questions/30851776/getting-jacoco-report-from-cucumber-tests-with-gradle

**Comment by tsundberg** [comment]
I don't know.

I propose that you give it a try. If there are any changes needed in this plugin, then please share a pull request with the desired changes.
